include $(srctree)/drivers/misc/mediatek/Makefile.custom
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/flashlight/src/mt6797/constant_flashlight/

obj-y += 		core.o 		\
			gpio.o 		\
			irq.o 	\
			file.o 		\
			input.o 	\
			pwm.o
