include $(srctree)/drivers/misc/mediatek/Makefile.custom
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/mt6735/$(ARCH_MTK_PROJECT)/dct/dct/

obj-y += 		core.o 		\
			gpio.o 		\
			irq.o 	\
			file.o 		\
			input.o 	\
			pwm.o
